
#Machine Energy Usage Config. This config is synced from server to client.
[usage]
	#Energy per operation tick (Joules). 50
	enrichmentChamber = "30"
	#Energy per operation tick (Joules). 100
	osmiumCompressor = "80"
	#Energy per operation tick (Joules). 50
	combiner = "30"
	#Energy per operation tick (Joules). 30
	crusher = "30"
	#Energy per operation tick (Joules). 50
	metallurgicInfuser = "30"
	#Energy per operation tick (Joules). 200
	purificationChamber = "170"
	#Energy per operation tick (Joules). 50
	energizedSmelter = "30"
	#Energy per operation tick (Joules). 100
	digitalMiner = "80"
	#Energy per operation tick (Joules). 100
	electricPump = "80"
	#Energy per operation tick (Joules). 50
	rotaryCondensentrator = "30"
	#Energy per operation tick (Joules). 200
	oxidationChamber = "170"
	#Energy per operation tick (Joules). 200
	chemicalInfuser = "170"
	#Energy per operation tick (Joules). 400
	chemicalInjectionChamber = "300"
	#Energy per operation tick (Joules). 50
	precisionSawmill = "30"
	#Energy per operation tick (Joules). 400
	chemicalDissolutionChamber = "300"
	#Energy per operation tick (Joules). 200
	chemicalWasher = "170"
	#Energy per operation tick (Joules). 400
	chemicalCrystallizer = "300"
	#Energy per operation tick (Joules). 50
	seismicVibrator = "30"
	#Energy per operation tick (Joules). 5
	pressurizedReactionBase = "3"
	#Energy per operation tick (Joules). 100
	fluidicPlenisher = "80"
	#Energy per operation tick (Joules). 10000
	laser = "8000"
	#Energy per operation tick (Joules). 100
	formulaicAssemblicator = "80"
	#Energy per operation tick (Joules). 100
	modificationStation = "80"
	#Energy per operation tick (Joules). 200
	isotopicCentrifuge = "170"
	#Energy per operation tick (Joules). 200
	nutritionalLiquifier = "170"
	#Energy per operation tick (Joules). 100000
	antiprotonicNucleosynthesizer = "80000"

	#Teleporter
	[usage.teleporter]
		#Base Joules cost for a teleportation.
		teleporterBase = "1000"
		#Joules per unit of distance travelled during teleportation - sqrt(xDiff^2 + yDiff^2 + zDiff^2).
		teleporterDistance = "10"
		#Flat additional cost for interdimensional teleportation.
		teleporterDimensionPenalty = "10000"

