
#General Regeneration Settings
[common]
	#The maximum regeneration capacity. This affects the durability of a Fob Watch and the amount of regenerations in a full cycle. Use 0 for infinite regenerations.
	#Range: > 0
	regenCapacity = 12
	#If this is false you won't lose your regenerations if you get killed during regeneration
	loseRegensOnDeath = false
	#Spawn fire during regeneration
	fieryRegen = true
	#Players are immune to fire damage while regenerating
	fireImmunity = false
	#config.regeneration.infinite_regenerations
	infiniteRegeneration = false
	#Sends a message to chat to say that a player is regenerating, and the reason for it
	sendRegenDeathMessages = true
	#This is where the regeneration skin folder will be generated, the default is './', the path MUST NOT end in /
	skinDir = "."
	#Toggle whether fob watches generate in some chest loot tables
	genFobLoot = true
	#Toggle whether mobs have regenerations. In most cases, requires a game restart.
	mobsHaveRegens = false

#Post Regen Settings
[post]
	#Amount of seconds the post-regeneration effect lasts
	#Range: > 0
	postRegenDuration = 360
	#The level of the regeneration status effect granted after you regenerate
	#Range: > 0
	postRegenLevel = 4
	#Regenerate hunger bars
	resetHunger = true
	#Regenerate Oxygen
	resetOxygen = true
	#The amount of absorption hearts you get when regenerating
	#Range: > 0
	absorbtionLevel = 10
	#List of potion effects the player can endure during post regeneration
	postRegenPotions = ["minecraft:weakness", "minecraft:mining_fatigue", "minecraft:resistance", "minecraft:health_boost", "minecraft:hunger", "minecraft:water_breathing", "minecraft:haste"]

#Grace Settings
[grace]
	#The time in seconds before your grace period enters a critical phase
	gracePhaseLength = 900
	#Chance that a player in critical phase gets damaged at a given tick. Higher number means more damage.
	#Range: > 0
	criticalDamageChance = 1
	#Interval (in seconds) at which your hands start to glow
	#Range: > 0
	criticalPhaseLength = 120
	#Amount of time (in seconds) you have when your hands start glowing before you start to regenerate
	#Range: > 0
	handTriggerDelay = 10

#Mid Regen Settings
[onRegen]
	#Upon regeneration every mob inside of this radius is immediately killed. Keep in mind that you should round up to accommodate for mobs that aren't standing in the center of a block
	#Range: > 0
	regenKillRange = 4
	#The amount of knockback every mob inside of the knock back radius gets
	regenerativeKnockback = 2.5
	#Range wherein every mob is knocked back upon regeneration
	#Range: > 0
	regenerativeKnockbackRange = 7
	#Players can be knocked back when too close to a regeneration
	regenerationKnocksbackPlayers = true
	#Toggle whether traits are enabled
	traitsEnabled = true
	#Toggle whether the server allows for players to fly upwards during certain Regeneration transitions
	upwardsMotion = true

