
#Client Regeneration Settings
[client]

	#Skin Settings
	[client.skin]
		#Disabling this will disable skin changing for you and you will retain your Mojang one
		changeMySkin = true
		#Changes the players perspective on regeneration
		changePerspective = true

		#Misc Settings
		[client.skin.misc]
			#Toggle whether re-skinned hearts render when you have Regenerations
			timelordRenderSecondLayers = true

